### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by Afanyiyu**

### CODE REVIEW

**Review by mausch — APPROVED** [review]

**Review by stakx — APPROVED** [review]
Thanks for fixing that link!

That second link to the Castle.IO project (fork?) is broken, too. Since your commit already touches that line, perhaps you could fix it too (or remove it altogether if no such project repo exists) while you're at it?

(Finally, a small remark about both links: it seems somewhat unusual to link to documentation in a fork's wiki from the main project repo. Would it be sensible to transfer that content here? Just for consideration. /cc @haf)

**Comment by Afanyiyu** [comment]
I also think some transformations is necessary. It's seems a bit weird that Issue and Wiki are in a fork repo.

**Comment by jonorossi** [comment]
> I also think some transfers are necessary. It seems a little strange that Issue and Wiki are in a fork repo.

Agreed, the docs should be moved to markdown files in a docs directory like other Castle projects. Did you want to submit another pull request.

**Comment by stakx** [comment]
OK if we merge this PR as is so we at least have working links again for the time being; then we'll adjust the links to the final location when content is transferred (in a separate PR)?

**Review by jonorossi — APPROVED** [review]

**Pull request merged**
